name: Block Merge on High or Critical Issues

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  block_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check Issue Tags
        id: check_issue_tags
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
                const { data: issue } = await github.rest.issues.get({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                });
                
                const issueTitle = issue.title;
                const hasHighOrCriticalTag = /\[(High|Critical)\]/i.test(issueTitle);
                
                if (!hasHighOrCriticalTag && issue.state === 'open') {
                  core.setFailed('Pull request cannot be merged because it has vulnerabilities in GitHub issues.');
                }

      - name: Merge Pull Request
        id: merge_pr
        run: echo "Pull request can be merged now."
