name: Block Merge on High or Critical Issues

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  block_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check Issue Tags
        id: check_issue_tags
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
                const { data: issues } = await github.rest.issues.listForRepo({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'open', // Filtrar apenas as issues abertas.
                });

                const hasHighOrCriticalIssue = issues.some((issue) => {
                  const issueTitle = issue.title;
                  return /\[(High|Critical)\]/i.test(issueTitle);
                });

                if (hasHighOrCriticalIssue) {
                  core.setFailed('Pull request cannot be merged because there are open issues with [High] or [Critical] tags in the repository.');
                }

      - name: Merge Pull Request
        id: merge_pr
        run: echo "Pull request can be merged now."
