name: Block Merge on High or Critical Issues

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  block_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check Issue Tags
        id: check_issue_tags
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const core = require('@actions/core');
            const github = require('@actions/github');
            
            async function run() {
              const issueNumber = github.context.payload.pull_request.number;
              const owner = github.context.repo.owner;
              const repo = github.context.repo.repo;
              
              try {
                const { data: issue } = await github.rest.issues.get({
                  owner,
                  repo,
                  issue_number: issueNumber
                });
                
                const issueTitle = issue.title;
                const hasHighOrCriticalTag = /\[(High|Critical)\]/i.test(issueTitle);
                
                if (hasHighOrCriticalTag) {
                  core.setFailed('Pull request cannot be merged because it has vulnerabilities in GitHub issues.');
                }
              } catch (error) {
                core.setFailed(`Error fetching issue details: ${error.message}`);
              }
            }
            
            run();

      - name: Merge Pull Request
        id: merge_pr
        run: echo "Pull request can be merged now."
